# Generated by Django 6.0.7 on 2026-08-06 02:27

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField()),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=150)),
                ('link_text', models.CharField(max_length=64)),
                ('body', martor.models.MartorField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=256)),
                ('description', martor.models.MartorField()),
                ('social_description', martor.models.MartorField()),
                ('url', models.URLField()),
                ('phone', models.CharField(max_length=25)),
                ('logo', models.ImageField(upload_to='')),
                ('active', models.BooleanField()),
                ('contact_form_email', models.EmailField(max_length=254)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='only_one_active')],
            },
        ),
    ]
