# Generated by Django 6.0.7 on 2026-07-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=3000)),
                ('social_description', models.CharField(max_length=3000)),
                ('url', models.URLField()),
                ('phone', models.CharField(max_length=25)),
                ('logo', models.ImageField(upload_to='')),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField()),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=150)),
                ('link_text', models.CharField(max_length=64)),
                ('body', models.CharField(max_length=3000)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
