# Generated by Django 6.0.7 on 2026-07-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirm', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='info',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='only_one_active'),
        ),
    ]
