# Generated by Django 6.0.7 on 2026-07-30 03:33

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirm', '0002_info_only_one_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='description',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='social_description',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='body',
            field=martor.models.MartorField(),
        ),
    ]
